name: "AutoReneraku"
description: "Automatic code review of Pharo Code using Reneraku Critiques"
author: badetitou
branding:
  color: orange
  icon: check-circle
runs:
  using: composite
  steps:
    - id: files
      uses: masesgroup/retrieve-changed-files@v3
      with:
        format: "space-delimited"
    - run: echo "changed_files=${{ steps.files.outputs.added_modified }}" >> "$GITHUB_ENV"
      shell: bash
    - run: $SMALLTALK_CI_VM $SMALLTALK_CI_IMAGE st ${{ github.action_path }}/ci/autoReneraku.st
      shell: bash
      env:
        PAT: ${{ inputs.pat }}
